### ISSUE TITLE
Default SSH Login Password

### ISSUE THREAD

**Issue by onet4** [tierra/wp-vagrant#10]
Hi,

How do I login to the boxes via SSH?

After I type `ssh wordpress-php53.local`, the console asks a password. What password should I put here?

**Comment by LPTT** [comment]
same problem here. The password vagrant only works for machine wordpress-php52.
I need it to connect mysql workbench, so vagrant ssh is no option.

**Comment by tierra** [comment]
As already mentioned, Vagrant relies on public key authentication. Specifically, there's a standard, known private key used for all typical Vagrant boxes, and it should already be available on your user account. Running `vagrant ssh-config [box]` will tell you where that private key is. It's often a file named `insecure_private_key`. Use it in your MySQL Workbench configuration:

![screenshot from 2015-01-21 12 34 49](https://cloud.githubusercontent.com/assets/106098/5843468/f32ab61c-a169-11e4-9b1b-2343696f8950.png)

Alternatively, you could just forward the MySQL port over from a local port by adding this to your Vagrantfile configuration for the intended box (this is not recommended though):

```
config.vm.network "forwarded_port", guest: 3306, host: 33060
```

Then you can just connect to localhost:33060 using your favorite MySQL tools.
