### ISSUE TITLE
box 'tierra/wordpress-php54' could not be found.

### ISSUE THREAD

**Issue by thinkocapo** [tierra/wp-vagrant#17]
Hello, I am trying to import this box 54 but I'm getting the following error, "The box 'tierra/wordpress-php54' could not be found." Any ideas?

We have current versions of Vagrant. We already cloned the dev repo to the wordpress folder, and added the address to our host file.

__educare@ubuntu:~/wp-vagrant$ vagrant up wordpress-php54
Bringing machine 'wordpress-php54' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'tierra/wordpress-php54' could not be found.__

**Comment by tierra** [comment]
You need to upgrade Vagrant to a more recent version.
