### ISSUE TITLE
Allow more databases to be created with 'wordpress' user

### ISSUE THREAD

**Issue by kminh** [tierra/wp-vagrant#18]
Hi, first I would like to thank you for all your work here.

Is it possible to allow more databases to be created with the `wordpress` user? Such change will  allow me to create a separate database for each version of WordPress I'm gonna test. Currently only `wordpress` and `wordpress-tests` can be created. Since I'm using the same build script on my machine as well as the Vagrant VMs, I don't want to use the `root` user because there are places I'm using the `root` user as well and it's not WordPress related.

I'm specifically refer to this snippet in your puppet file:

```
mysql::db { ['wordpress', 'wordpress-tests']:
  ensure   => present,
  charset  => 'utf8',
  user     => 'wordpress',
  password => 'wordpress',
  host     => 'localhost',
  grant    => ['ALL'],
  require  => Class['mysql::server']
}
```

Thanks for your consideration.

**Comment by tierra** [comment]
If you're looking at running several different versions of WordPress in the same Vagrant image, you might want to consider using VVV instead. It's better geared for that kind of development:
https://github.com/Varying-Vagrant-Vagrants/VVV

Another option to consider might be cloning this repo to another location with your other version of wordpress, and provisioning another box for it, but you'll still run into IP conflicts if you try to run them at the same time.

**Comment by kminh** [comment]
VVV seems to only support one version of PHP.

I'm already using a fork of this project, but just want to ask if you would consider making such change. Maybe just an `exec` line in puppet files:
```
class mysql::server {
      exec { "grant-db":
        command => "/usr/bin/mysql -uroot -e \"grant all on *.* to wordpress@localhost identified by 'wordpress';\""
      }
}
```

**Comment by tierra** [comment]
I could probably look at just defining the `wordpress` user as a more generic account that has the same permissions as root mostly. That would be fine, but you'd likely still be creating your additional databases yourself (sounds like you're fine with that though).

I'm still confused as to why you don't feel that the pre-configured root user is adequate for this. You're using these Vagrant boxes for purposes *other* than WordPress even though these are designed specifically just for WordPress? Doesn't seem like something I should care to support in these boxes.

**Comment by kminh** [comment]
The root user has `wordpress` as its password, and that makes sense for these boxes. When I test my plugins, for example, I use one single build script and run it in both my environment and environments created by these boxes. Normally in my environment I would use `root` as password for the root user, and this root user is used in many places, unrelated to WordPress, so I have to:
* either use `wordpress` as password in my environment as well
* or modify the build script to support both passwords
Both are not ideal IMO.

Does that make sense?

**Comment by tierra** [comment]
> or modify the build script to support both passwords

You are running it in two different environments, supporting different credentials for each would be entirely normal and expected. For example, I often provide a `phpunit.xml.dist` file with some default environment variables defining credentials for MySQL on Travis CI, and then I copy the file to `phpunit.xml` locally (which is included in `.gitignore`) and modify it with the credentials for these boxes, and use that for local builds instead. You can also do the same with `wp-config.php` (and `wp-tests-config.php`).

**Comment by kminh** [comment]
I believe not all build scripts can support multiple config files like PHPUnit, and things can get pretty messy if they don't.

Hopefully you can make a change, but it's fine if you find it's not necessary.

**Comment by tierra** [comment]
> I believe not all build scripts can support multiple config files like PHPUnit

PHPUnit doesn't, and that's kind of my point. Your tools don't need any kind of special features to support it, it's entirely based on how you structure you workflow, set environment variables, and write your build scripts that provide this kind of flexibility. Just don't use fixed values, that's all it really takes.

In any case, I will adjust the default accounts (both root and wordpress) to provide more liberal permissions by default (hence why this ticket is still open), but there's really nothing stopping you from making this work right now.

**Comment by kminh** [comment]
Hmm doesn't PHPUnit allow you to:

* use different config file with `-c` option
* use `phpunit.xml.dist` as a base, and then users can customize with a local `phpunit.xml` (and is put in `.gitignore` in your case).

That's what I meant by multiple config files and if other build scripts support that I would be happy to use them in my workflow.

Thank you for your consideration, will keep an eye on this issue.
